Revocation Test Development and Infrastructure
openwallet-foundation/owl-agent-test-harness pull request #106
Opened 2020-10-09 21:05 UTC by nodlesh

Working revocation test scenario and infrastructure. 
Includes ConfigArgParser in requirements for acapy config files.
Tails server usage integrated into manage script
Updated readme for Tails Server usage
Includes the ability to switch operations if different between Acapy Versions. (this will only work on official releases at this point until master reports something different than the previous release)

2020-10-13 19:57 UTC, swcurran requested changes
Looks like there are some LGTM bot cleanups and then this looks good to go.

2020-10-13 19:57 UTC, swcurran commented on aries-backchannels/acapy/acapy_backchannel.py
> +        log_msg('Recieved a Connection Webhook message: ' + json.dumps(message))
Typo - received

2020-10-13 19:57 UTC, swcurran commented on aries-backchannels/acapy/acapy_backchannel.py
> +        log_msg('Recieved Issue Credential Webhook message: ' + json.dumps(message))
More of them too.

2020-10-14 18:39 UTC, nodlesh commented
@swcurran Should be good to go.

2020-10-14 19:52 UTC, swcurran approved these changes
Thanks

2020-10-14 19:53 UTC, merged