feat: oob connectionless for issue cred and present proof
openwallet-foundation/owl-agent-test-harness pull request #474
Opened 2022-04-10 17:15 UTC by TimoGlastra

Adds connectionless support for both issue credential v1/v2 and present proof v1/v2 using the oob protocol. Also removed the old AIP 1 connectionless code as it was never used.

Draft for now as it's built against my fork of ACA-Py until it get's merged into main.

This only handles attachments in OOB invitations for connectionless. Probably good to also add tests for receiving oob invitations with creating a connection and processing an attachments (Should be quite easy now with all substeps being defined).

One thing I ran into and we should probably change is that AATH is build on the expectation that the oob receive invitation will return a connection record and also connection state instead of oob state. Probably because that's how it was implemented in ACA-Py. For now I've tricked the ACA-Py backchannel into returning the state it expects for now (mapping `prepare-response` to `invitation-received`), but would be good to change this to be more in line with the RFC (having less ACA-Py driven backchannel API design would be good in general I think)

We may want to move some tests from the DIDExchange tests to the oob tests now that there is a dedicated file for out of band

2022-04-11 14:22 UTC, nodlesh submitted a review, later dismissed
Thanks for updating these!

2022-04-11 14:23 UTC, nodlesh commented
Sorry, didn't notice it's draft.

2022-05-30 14:37 UTC, ianco commented
Noticed a few conflicts, related to code formatting so maybe a different black version?

2022-05-30 14:56 UTC, TimoGlastra commented
I think we're not enforcing black for this repo, so that's probably why? I'll see to address the conflicts tomorrow!

2022-06-11 21:43 UTC, swcurran commented
Let us know when it is past draft. A little worried that existing tests broke because of the ACA-Py PR. Does that mean a breaking change for controllers or is it just AATH?

2022-06-12 08:21 UTC, TimoGlastra commented
Away from my computer until Tuesday, will take a look at the conflicts then

2022-06-12 16:59 UTC, swcurran commented
Adding note on this PR for completeness.  The [ACA-Py "connectionless" PR](https://github.com/hyperledger/aries-cloudagent-python/pull/1710) has been merged, and that generated a number of ACA-Py to ACA-Py DID Exchange errors.  Testing on this branch does not seem to fix the errors.

2022-06-13 17:11 UTC, swcurran requested changes

2022-06-13 17:11 UTC, swcurran commented on aries-backchannels/acapy/requirements-main.txt
> +aries-cloudagent[indy, bbs, askar]@git+https://github.com/TimoGlastra/aries-cloudagent-python@fix/oob-connectionless
This needs to be changed before merging.

2022-06-14 21:49 UTC, swcurran approved these changes
Tested for all ACA-Py - ACA-Py tests.  Working.  w00t!!

2022-06-14 21:49 UTC, merged