[hyperledger #560] Change the order of the connection steps to improve mobile testing flow
openwallet-foundation/owl-agent-test-harness pull request #586
Opened 2022-10-27 19:29 UTC by PatStLouis

This partially resolves issue 560 more specifically the second task listed.

I was able to run a combination of mobile tests with acapy/javascript as backchannels without issue.

Signed-off-by: Patrick St-Louis <patrick.st-louis@idlab.org>

2022-10-27 19:39 UTC, PatStLouis commented
For context, what these changes do is change the order of the actions taken when 2 connections are required for issuing/presenting.

It used to go
1. Connect with Acme
2. Connect with Faber
3. Receive Credential from Acme
4. Receive Proof Request from Faber

To a more mobile friendly order:
1. Connect with Acme
2. Receive Credential from Acme
3. Connect with Faber
4. Receive Proof Request from Faber

2022-10-28 17:31 UTC, nodlesh requested changes
This doesn't have any side effects on framework to framework interop testing outside of mobile.  However you will need to add the when clause to 0160-connection.py
`@when('"{sender}" and "{receiver}" have an existing connection')`
above
`@given('"{sender}" and "{receiver}" have an existing connection')`

I don't think the mobile tests will work without this either.

2022-11-22 17:12 UTC, PatStLouis commented
@nodlesh I've made the changes requested and tested them, everything seems to work as intended. Looking forward to review this at the next AATH meeting.

2022-11-22 17:14 UTC, nodlesh approved these changes
Awesome.

2022-11-23 13:53 UTC, nodlesh commented
@PatStLouis We need the commits signed to pass DCO.

2022-11-23 14:31 UTC, PatStLouis commented
@nodlesh I just double checked and both commits in this PR are signed

2022-11-23 15:07 UTC, nodlesh commented
Weird. Anyone know why DCO is stuck, and how to proceed?

2022-11-23 15:47 UTC, merged