fix-646: Implemented Re-try failed scenarios
openwallet-foundation/owl-agent-test-harness pull request #724
Opened 2023-08-24 20:07 UTC by geethutnair94

Fix for the [issue ](https://github.com/hyperledger/aries-agent-test-harness/issues/646)

Changes made
1) Added a before_feature hook to implement retry failed scenarios.
2) Passing the overriding variable TEST_RETRY_ATTEMPTS_OVERRIDE via manage.py to docker environment

Note : Found $DOCKER_ENV is not passed to the docker run command on runTests() function. So adding that too.

How to run:
There are two ways to overide the no of attempts for re-try failed scenarios

1) Add the variable **test_retry_attempts** in the **behave.ini** like below

> test_retry_attempts = 2

2) Pass the variable **TEST_RETRY_ATTEMPTS_OVERRIDE** as environment variable while running test or through deployment yaml files.

> eg: TEST_RETRY_ATTEMPTS_OVERRIDE=2 ./manage run -d acapy -b javascript -t @AcceptanceTest

Screenshots

![image](https://github.com/hyperledger/aries-agent-test-harness/assets/79985154/6742443e-4260-46cc-8017-46ec3264dc6c)
![image](https://github.com/hyperledger/aries-agent-test-harness/assets/79985154/650ce2cd-d041-4c82-bb3a-5246d06a1b3d)
![image](https://github.com/hyperledger/aries-agent-test-harness/assets/79985154/c0abf141-7400-4b3e-b9cd-eeab3061fa65)
![image](https://github.com/hyperledger/aries-agent-test-harness/assets/79985154/c35a3f08-400b-4a83-9fbf-3dbf99c2f770)

2023-08-24 21:41 UTC, esune commented
Tagging @nodlesh for review

2023-08-25 12:49 UTC, nodlesh commented
Looks good @geethutnair94. I am testing this out now, but in the meantime could you add an .md file documenting how to use it? Pretty much the same stuff as you have in the description of this ticket.

2023-08-25 14:05 UTC, nodlesh requested changes
Works well. With an .md explaining how to use it, I will approve and merge. 

The .md should mention that the variable should go under the `[behave.userdata]` section of the behave.ini file.

2023-08-28 20:30 UTC, geethutnair94 commented
@nodlesh Thanks for the review I added a .md document explaining the changes made and how to run.
Please review it

2023-08-28 21:09 UTC, nodlesh approved these changes
Awesome, thanks!

2023-08-28 21:10 UTC, merged